### ISSUE TITLE
Ask a question

### ISSUE THREAD

**Issue by mini120955** [ai-aimbot/AIMr#64]
Which version of python environment do you compile opencv and run AIM? When I compiled cmake, I found that the 3.12 version of python did not have the BUILD_opencv_python3 option.

**Comment by kbdevs** [comment]
> Which version of python environment do you compile opencv and run AIM? When I compiled cmake, I found that the 3.12 version of python did not have the BUILD_opencv_python3 option.

please join the discord. https://discord.gg/AIMr
