### ISSUE TITLE
This is a risky program. Don't download it.

### ISSUE THREAD

**Issue by JasonLeong1999** [ai-aimbot/AIMr#72]
Identifikasjon inneholder trojanske virus, noe som kan føre til trojanske virus invaderer din
systemet og til og med stjele kontopassord, private bilder og annen privat informasjon.
Trojan fil: = AIMr.zipAIMr.exe
Risikoadvarsel: Trojan Win64/Heur.Generic.H8 oAgrcA)

The same features of aimmy are free and virus-free and risk-free!

**Comment by kbdevs** [comment]
this isn't a virus we literally have 5k+ discord members, stop talking if you aren't even right
